### ISSUE TITLE
Process hanging waiting for network confirmation

### ISSUE THREAD

**Issue by mgrecar** [luciusbono/Packer-Windows10#29] opened 2018-12-05 21:20 UTC
I kicked things off following the steps on the README, and when I got to `Waiting for WinRM to become available`, I let it sit for a while, expecting a long wait for updates, as described.

4 hours later, no appreciable progress.  I opened up VirtualBox and hit Show, and it turns out it was hung up waiting on user input.  It showed the network I was on and was waiting to select the `Next` button.  I manually hit the button and let it go, and it went along through downloading and installing updates, rebooting, etc.

It looks like it might need a tweak to get past this step?  I don't know PowerShell so I am at a loss as to offering up a PR.  I am currently on wifi at work, and there's multiple possible networks, so that perhaps is a difference that you might not be experiencing?

   - Using MacOS 10.14.1 Mojave
   - Packer version 1.3.2
   - Vagrant version 2.2.2
   - Oracle VirtualBox version 5.2.22

**Comment by luciusbono** [comment] 2018-12-21 07:17
Hmm, I'm unable to replicate this myself (and apologies for the late response). I'm running through it on VirtualBox on Windows, but I'll pull this down on a Mac running virtualbox 5.2.22 tomorrow and see if I can get it to misbehave. 

So it wasn't a Yes / No dialog, it was a Next type dialog? Was it asking to specify the network type?

**Comment by mgrecar** [comment] 2018-12-21 14:27
No worries!  It was definitely a Next type dialog, I just had to hit that manually to advance with no other issues.  It was really just mirroring back the name of the wireless network, so I am not sure exactly what configuration could be changed at that point.  I should have taken a screenshot 🤦‍♂️

**Comment by luciusbono** [comment] 2018-12-21 16:42
Huh. That's interesting! I'm wasn't aware that the VM could be made aware
of the WiFi network - I thought it just saw a generic wired LAN adapter.
Maybe this is a newish Virtualbox thing on macOS. I'll build a test VM
today and let you know the results.

**Comment by luciusbono** [comment] 2018-12-21 21:53
Wasn't able to replicate the problem. The build did take quite a while (close to an hour and a half), but I'd chaulk that up to my build machine more than anything (2018 MacBook Air). 

Here was my test environment: 

macOS `10.14.2`
Virtualbox `5.2.22 r126460`
Vagrant `2.2.2`
Packer `1.3.3`
Windows 10 ISO: `17763.107.101029-1455.rs5_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso` with an MD5 of `89ab238e51f0af6e72c8b7115de03154`

I pulled down that Windows ISO today, maybe it'd be worth a try grabbing a new one?

**Comment by tedsmitt** [comment] 2019-02-13 19:23
I managed to skip the network dialogue by adding the following tags into the `<OOBE></OOBE>` section in the autoattend.xml file:

`<SkipMachineOOBE>true</SkipMachineOOBE>`
`<SkipUserOOBE>true</SkipUserOOBE>`
`<HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>`

Once it booted up I could see the FirstlogonScript running and everything running as expected.

**Comment by luciusbono** [comment] 2020-08-24 18:55
Closing this issue as I can't reproduce it. I believe SkipUserOOBE and SkipMachineOOBE are deprecated, and I just tested this again with Windows 10 2004 Enterprise and had no issues. LMK if this continues to be an issue for you and I will do my best to troubleshoot it.

**Closed as completed by luciusbono** 2020-08-24 18:55 UTC
